name: track-github-issues
description: Track GitHub issues across organizations based on user assignments.
author: Sarthak Kapoor

inputs:
  users:
    description: Comma-separated list of GitHub user  names to query for assigned open issues.
    required: true
  organizations:
    description: Comma-separated list of organization names to filter search. Optional.
    required: false
    default: ""
  per_page:
    description: Results per page (used to compute effective limit). Optional.
    required: false
    default: "100"
  page_limit:
    description: Number of pages to fetch (used to compute effective limit). Optional.
    required: false
    default: "10"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install package
      shell: bash
      env:
        # to avoid issues with setuptools_scm dynamic versioning
        SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0"
      run: |
        pip install ${{ github.action_path }}

    - name: Run GitHub issue tracker
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        track-github-issues \
          --users "${{ inputs.users }}" \
          --orgs "${{ inputs.organizations }}" \
          --per-page "${{ inputs.per_page }}" \
          --page-limit "${{ inputs.page_limit }}" \
          --gh-token "${{ env.GH_TOKEN }}"
